### ISSUE TITLE
How do I directly import or open this project in Android Studio?

### ISSUE THREAD

**Issue by YogKar** [georgik/LampAndroidApp#1]

**Comment by georgik** [comment]
Hi @YogKar 

Thank you for pointing out the problem. The issue was caused by missing settings.gradle.

I've added the file and fixed some dependencies. You should be able to compile the application. 

Let me know whether the correction works for you.

**Comment by georgik** [comment]
Information how to resolve similar issue added to article: http://georgik.rocks/missing-run-or-debug-action-in-android-studio/
